typography_spectrum: 0.708852207986638
color:
  brandStrength: 0.5468430311884731
  lightness: 0.5259115903172642
  saturation: 0.2973553645424545
  rhythmicContrast: 0.32953610247932374
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
layout_spectrum: 0.12576823076233268
analytics:
  google: UA-78518104-1
author:
  name: Andre Amorim
  email: andre@amorim.me
  url: amorim.me
name: MLM
navigation:
  - name: Youtube Channel
    url: 'https://www.youtube.com/channel/UCilprwYUC_btSGxybDMNM7g'
    type: external
title: 'artificial intelligence, machine learning, bigdata, news'
